services:
  redmine:
    image: redmine
    container_name: redmine_app
    restart: always
    ports:
      - 8089:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    networks:
      - redmine_net
  db:
    image: mysql:8.0
    container_name: redmine_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 10s
      start_period: 20s # Tăng thời gian để MySQL khởi động đầy đủ
    networks:
      - redmine_net


networks:
  redmine_net:
    driver: bridge