version: '3.1'

services:
  db:
    image: nguyen0710/odoo_db_hub:v1
    container_name: odoo_db
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: nguyen0710/odoo_web_hub:v1
    container_name: odoo_web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
