services:
  mysqldb:
    image: mysql:5.7
    container_name: espocrm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm
      MYSQL_PASSWORD: espocrm
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 10s
      start_period: 20s # Tăng thời gian để MySQL khởi động đầy đủ
    networks:
      - espocrm_net

  espocrm:
    image: nguyen0710/espocrm:v1
    container_name: espocrm-web
    restart: always
    ports:
      - "8087:80"
    environment:
      - ESPOCRM_DATABASE_HOST=mysqldb
      - ESPOCRM_DATABASE_PORT=3306
      - ESPOCRM_DATABASE_NAME=espocrm
      - ESPOCRM_DATABASE_USER=espocrm
      - ESPOCRM_DATABASE_PASSWORD=espocrm
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - espocrm_net
networks:
  espocrm_net:
    driver: bridge
