version: '3.8'

services:
  wordpress:
    image: nguyen0710/wordpress_hub_wordpress:v1
    container_name: wordpress_test
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress

  db:
    image: nguyen0710/wordpress_hub_mysql:v1
    container_name: mysql_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
