services:
  magento_web:
    image: nguyen0710/magento_apache:v1
    container_name: magento_apache
    ports:
      - "8084:80"                   # Map port host 8084 -> container 80
    depends_on:
      magento_mariadb:
        condition: service_healthy
      magento_opensearch:
        condition: service_healthy
      magento_redis:
        condition: service_healthy
    command: >
      sh -c "dockerize -wait tcp://magento_mariadb:3306 -wait tcp://magento_opensearch:9200 -wait tcp://magento_redis:6379 -timeout 60s && echo '✅ All dependencies are ready. Starting Apache...' && apache2-foreground"

    environment:
      - MYSQL_HOST=magento_mariadb
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - OPENSEARCH_HOST=magento_opensearch
      - RABBITMQ_HOST=magento_rabbitmq
      - REDIS_HOST=magento_redis
      - MAGENTO_BASE_URL=${MAGENTO_BASE_URL}
    healthcheck:
      disable: true
    networks:
      - magento_net

  magento_mariadb:
    image: nguyen0710/magento_mariadb_hub:v1
    container_name: magento_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 10s
      start_period: 20s # Tăng thời gian để MySQL khởi động đầy đủ
    networks:
      - magento_net

  magento_opensearch:
    image: nguyen0710/magento_opensearch:v1
    container_name: magento_opensearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 20s
    networks:
      - magento_net

  magento_redis:
    image: nguyen0710/magento_redis:v1
    container_name: magento_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 3s
      start_period: 20s
    networks:
      - magento_net

  magento_rabbitmq:
    image: nguyen0710/magento_rabbitmq:v1
    container_name: magento_rabbitmq
    restart: always
    networks:
      - magento_net

networks:
  magento_net:
    driver: bridge